// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgBzkum-9ZsxdYfS5N4xhXrvta-J6Gw5A',
    appId: '1:310954031443:web:d1fb31448b4202aa55c9a6',
    messagingSenderId: '310954031443',
    projectId: 'task-app-b53c2',
    authDomain: 'task-app-b53c2.firebaseapp.com',
    storageBucket: 'task-app-b53c2.appspot.com',
    measurementId: 'G-K82NJJCRZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxPchgJvqetbwx5UxrzfbhAQo7ZaQ5LC0',
    appId: '1:310954031443:android:fe59bc0de7042ca055c9a6',
    messagingSenderId: '310954031443',
    projectId: 'task-app-b53c2',
    storageBucket: 'task-app-b53c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOzly1lWAvrOtZxYjCx3DShq4TqMksJRA',
    appId: '1:310954031443:ios:48d282aeece5f98a55c9a6',
    messagingSenderId: '310954031443',
    projectId: 'task-app-b53c2',
    storageBucket: 'task-app-b53c2.appspot.com',
    iosClientId: '310954031443-jqimnpoa5scvscsq3qaog5i5v8dv0dve.apps.googleusercontent.com',
    iosBundleId: 'com.example.omegaTask',
  );
}
